version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github:
        patterns:
          - "actions/*"
      docker:
        patterns:
          - "docker/*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns:
          - "*"
